logging:
  level:
    web: DEBUG
eureka:
  client:
    prefer-same-zone-eureka: false
    serviceUrl:
      defaultZone: https://${MIP:localhost}:8761/eureka/

server:
  port: 8888
  ssl:
    enabled: true
    key-store: classpath:client.p12
    key-password: 123456
    key-store-password: 123456
    key-alias: client
    key-store-type: PKCS12

spring:
  application:
    name: API_GATEWAY
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes:
      - id: USER_SERVICE
        uri: http://${USIP:localhost}:8082
        predicates:
        - Path=/user/**

      - id: ADMIN_SERVICE
        uri: http://${ASIP:localhost}:8083
        predicates:
        - Path=/admin/**
