version: "3"
services:
  API_GATEWAY:
    image: api_gateway
    container_name: api_gateway
    networks:
      - microservices
    ports:
      - "8888:8888"

  USER_SERVICE:
    image: user_service
    container_name: user_service
    networks:
      - microservices
    ports:
      - "8082:8082"

  ADMIN_SERVICE:
    image: admin_service
    container_name: admin_service
    ports:
      - "8083:8083"
    networks:
      - microservices

networks:
  microservices: