logging:
  level:
    web: DEBUG
eureka:
  client:
    prefer-same-zone-eureka: false
    serviceUrl:
      defaultZone: http://${MIP:localhost}:8761/eureka/

server:
  port: 8082

spring:
  application:
    name: USER_SERVICE

